// Generated by CoffeeScript 1.9.3
(function() {
  var AllowedOrigins, ORIGIN_REGEXP, filterForTorflixTabs, getTorflixTabs, isTorflixUrl, originOfUrl;

  AllowedOrigins = {};

  AllowedOrigins['torflix.jaredatron.com'] = true;

  AllowedOrigins['torflix.dev'] = true;

  ORIGIN_REGEXP = /^[^\/]*:\/\/([^\/]+)/;

  ​;

  originOfUrl = function(url) {
    return url.match(ORIGIN_REGEXP)[1];
  };

  ​;

  isTorflixUrl = function(url) {
    return AllowedOrigins[originOfUrl(url)];
  };

  ​;

  filterForTorflixTabs = function(tabs) {
    return tabs.filter(function(tab) {
      return isTorflixUrl(tab.url);
    });
  };

  ​;

  getTorflixTabs = function(callback) {
    chrome.tabs.query({}, function(tabs) {
      callback(filterForTorflixTabs(tabs));
    });
  };

  ​;

  chrome.tabs.onUpdated.addListener(function(tabId, changes, tab) {
    if (changes.status === 'complete' && isTorflixUrl(tab.url)) {
      console.info('FOUND ONE', tab);
      return chrome.tabs.executeScript(null, {
        file: 'tab.js'
      });
    }
  });

  ​;

}).call(this);
